feat(delete product): implement delete product feature
willywax/NextProduct pull request #18
Opened 2019-08-23 13:38 UTC by j0flintking02

#### What does this PR do?
#### Description of Task to be completed?
- ensure that only the owner can delete their product
- implement error handling for failed delivery
#### How should this be manually tested?
- pull the branch locally
- ensure the database and env variables are add
- run npm test
# What are the relevant pivotal tracker stories?
[Delivers #167944545](https://www.pivotaltracker.com/story/show/167944545)
# screenshots
<img width="1134" alt="Screen Shot 2019-08-23 at 15 37 01" src="https://user-images.githubusercontent.com/26383328/63596615-ebf88600-c5bb-11e9-9ce9-02bde77272cb.png">

2019-08-23 13:48 UTC, willywax approved these changes
Looks good

2019-08-26 14:27 UTC, Bahatiroben approved these changes
looks fine

2019-08-26 15:20 UTC, drayzii requested changes

2019-08-26 15:20 UTC, drayzii commented on backend/controllers/ProductController.js
> +        data: deleteStatus,
I don't think you should return data when something is deleted... I think it only returns a boolean value

2019-08-27 11:03 UTC, drayzii approved these changes

2019-08-27 11:03 UTC, merged