Ch setup travis # #167977789
willywax/NextProduct pull request #6
Opened 2019-08-20 19:32 UTC by willywax

#### What does this PR do?
Set Up Travis , Coverall and Code Climate
#### Description of Task to be completed?
Integrated Travis, Coveralls and Code Climate 
Add badges for Travis, Coveralls and Code Climate
#### How should this be manually tested?
Badges should display on develop readme
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[##167977789]

2019-08-20 19:35 UTC, j0flintking02 commented
squash you commit please

2019-08-20 19:45 UTC, Bahatiroben approved these changes
The tests are ok. It is good. Yet you have bunch of commits. You may squash them into one.

2019-08-21 07:32 UTC, Dkabiswa commented on .travis.yml
> +  - yarn test
let us stick to npm package

2019-08-21 07:34 UTC, Dkabiswa requested changes
let us stick to npm

2019-08-21 07:34 UTC, drayzii approved these changes

2019-08-21 07:36 UTC, Dkabiswa approved these changes
LGTM

2019-08-21 07:36 UTC, merged